- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
      region: "{{ aws_region }}"
  tasks:

    - name: Create internet gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc.vpc.id}}"
        tags:
          Name: Ansible Project5 gateway
          Project: "5"
        region: "{{ aws_region }}"
        state: present
      register: igw

    - name: Create NAT gateway
      ec2_vpc_nat_gateway:
        subnet_id: "{{ public_subnet_1.subnet.id }}"
        region: "{{ aws_region }}"
        if_exist_do_not_create: yes
        state: present
      register: nat
#    - name: debug
#      debug: var=nat

