- hosts: localhost
  gather_facts: no
  vars:
    aws_region: "us-west-1"
  module_defaults:
    group/aws:
        region: "{{ aws_region }}"
  tasks:

    - name: Create public route table
      ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        region: "{{ aws_region }}"
        tags:
          Name: Ansible-public-rt
        subnets:
          - "{{ public_subnet_1.subnet.id}}"
          - "{{ public_subnet_2.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        state: present
      register: public_route_table
#    - name: debug
#      debug: var=public_route_table



    - name: Create private route table 1
      ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        region: "{{ aws_region }}"
        tags:
          Name: Ansible-private-rt-1
        subnets:
          - "{{ private_subnet_1.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat.nat_gateway_id }}"
        state: present
      register: private_nat_route_table_1
#    - name: debug
#      debug: var=private_nat_route_table_1

    - name: Create private route table 2
      ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        region: "{{ aws_region }}"
        tags:
          Name: Ansible-private-rt-2
        subnets:
          - "{{ private_subnet_2.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat.nat_gateway_id }}"
      register: private_nat_route_table_2
#    - name: debug
#      debug: var=private_nat_route_table_2