---
version: "3.8"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: "xF8l6v0CxwI"
      POSTGRES_USER: image_gallery
      POSTGRES_DATABASE: image_gallery
      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - node.labels.database==yes
    secrets:
      - ig_password
    volumes:
      - "/mnt/efs:/var/lib/postgresql/data"
      - "/run/secrets
#     - /create_tables.sql:/docker-entrypoint-initdb.d



volumes:
  database:
    external: true

secrets:
  ig_password:
    external: true