FROM ubuntu:latest



# Install dependencies
#RUN apt-get update &&


RUN apt-get update -y && apt-get install -y python3 python3-pip



COPY  gallery /app/gallery
COPY requirements.txt /app/
WORKDIR /gallery
RUN pip3 install -r requirements.txt

ENV FLASK_APP=/ui/app.py
ENV FLASK_ENV=development

EXPOSE 8888
# Boot Command
CMD ["uwsgi", "--http", "--host", "0.0.0.0"]
