---
version: "3"

services:

#  db:
#    image: demo-postegres
#    user: "32767"
#    volumes:
#      - "/home/ec2-user/secrets:/mnt/secrets"
#      - "demo-postgres:/var/lib/postgresql/data"
#
#
#  web:
#    image: image_gallery
#    user: "32767"
#    environment:
#      PG_HOST: "db"
#      PG_PORT: "5432"
#      IG_USER: "postgres"
#      IG_PASSWD_FILE: "/mnt/secrets/postgres_passwd"
#      IG_DATABASE: "postgres"
#    ports:
#      - "5000:8888"
#    volumes:
#      "/home/ec2-user/secrets:/mnt/secrets"
#    depends_on:
#      - "db"
#
#  volumes:
#    demo-postgres:
#      external: true
#


---
version: "3.8"

services:
  registry:
    image: registry:latest
    ports:
      -"5000:5000"
    deploy:
      replicas: 1
      placement:
        constraint:
          - node.role==manager
    environment:
      REGISTERY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry
    volumes:
      -"registery:/mnt/gallery"
#  pinger:
#    image: "localhost:5000/net"
#    command: ["ping", "google.com"]
#    deploy:
#      mode: global
#    depends_on:
#      - "registry"
  db:
    image: "postgres"
    environment:
      PG_HOST: "db"
#      PG_PORT: "5432"
      IG_USER: "postgres"
      IG_PASSWD_FILE: "/mnt/secrets/postgres_passwd"
      IG_DATABASE: "postgres"
      PG_DATA: /var/lib/postgresql/data/pgdata
    deploy:
      mode: "replicated"
      replicase: 1
      placement:
        constraints:
          - node.labels.postgres_server==yes


