---
version: "3.8"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: database
      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - node.labels.database==yes
    secrets:
        - ig_password
    volumes:
      - "/mnt/efs:/var/lib/postgresql/data"
      - "/create_db.sh:/docker-entrypoint-initdb.d"

  image_gallery:
    image: "postgres:11"
    environment:
      IG_PASSWORD: ig_password
      IG_USER: image_gallery
      POSTGRES_DATABASE: image_gallery
    deploy:
      mode: "replicated"
      replicas: 0
    secrets:
      - ig_password
    volumes:
      - "/app/creat_db.sh"
    ports:
      - target: 5000
        published: 8888
        mode: host
        protocol: tcp

  flask:
    image: "localhost:5000/flask"
    deploy:
      placement:
        constraints:
          - node.labels.flask_server==yes
    secrets:
      - ig_password


volumes:
  database:
    external: true

secrets:
  ig_password:
    external: true