---
version: "3.8"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: database
#      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - node.labels.database==yes
    secrets:
        - source: "ig_password"
        - target: "/docker-entrypoint-initdb.d/create_db.sh"
        - uid: "0"
    volumes:
      - "/mnt/efs:/var/lib/postgresql/data"
#      - "/run/secrets
#     - "/create_db.sql:/docker-entrypoint-initdb.d



volumes:
  database:
    external: true

secrets:
  ig_password:
    file: create_db.sh