---
version: "3.8"

services:

  database:
    image: "postgres:11"
    environment:
      POSTGRES_PASSWORD: "xF8l6v0CxwI"
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - node.labels.database==yes
    volumes:
      - "/mnt/efs:/var/lib/postgresql/data"

volumes:
  database:
    external: true