---
version: "3"

services:

  database:
    image: "postgres"
    user: "32767"
    volumes:
      - "/home/ec2-user/ /mnt/efs/postgres-data"
      - "postgres:/var/lib/postgresql/data"
    environment:
      PG_HOST: "db"
      #      PG_PORT: "5432"
      PG_USER: "postgres"
      PG_PASSWORD: "xF8l6v0CxwI"
      PG_DATABASE: "postgres"
      PG_DATA: /var/lib/postgresql/data/pgdata
      deploy:
        mode: "replicated"
        replicas: 1
        placement:
          constraints:
            - node.labels.postgres_server==yes
      volumes:
        "/home/ec2-user/python-image-gallery:/var/lib/postgresql/data"
      depends_on:
        - "database"
#  web:
#    image: image_gallery
#    user: "32767"
#    environment:
#      PG_HOST: "db"
#      PG_PORT: "5432"
#      IG_USER: "postgres"
#      IG_PASSWD_FILE: "/mnt/secrets/postgres_passwd"
#      IG_DATABASE: "postgres"
#    ports:
#      - "5000:8888"
#    volumes:
#      "/home/ec2-user/secrets:/mnt/secrets"
#    depends_on:
#      - "db"

#  volumes:
#    postgres:
#      external: true



#---
#version: "3.8"

#services:
##
#  db:
#    image: "postgres"
#    environment:
#      PG_HOST: "db"
##      PG_PORT: "5432"
#      IG_USER: "postgres"
#      IG_PASSWD_FILE: "/mnt/secrets/postgres_passwd"
#      IG_DATABASE: "postgres"
#      PG_DATA: /var/lib/postgresql/data/pgdata
#    deploy:
#      mode: "replicated"
#      replicase: 1
#      placement:
#        constraints:
#          - node.labels.postgres_server==yes


