---
version: "3"

services:

#  registry:
#    image: registry:latest
#    ports:
#      -"5000:5000"
#    deploy:
#      replicas: 1
#      placement:
#        constraint:
#          - node.role==manager
#    environment:
#      REGISTERY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /mnt/registry
#    volumes:
#      -"registery:/mnt/gallery"
  database:
    image: "postgres"
    environment:
      PG_PASSWORD: "xF8l6v0CxwI"
      PG_USER: postgres
      PG_DATABASE: postgres
      PG_DATA: /var/lib/postgresql/data/pgdata
    deploy:
      mode: "replicated"
      replicas: 1
      placement:
        constraints:
          - node.labels.postgres_server==yes
    volumes:
      - "/mnt/efs/postgres-data:/var/lib/postgresql/data"

  volumes:
    postgres:
      external: true