FROM ubuntu:latest



# Install dependencies
#RUN apt-get update &&


RUN apt-get update -y && apt-get install python3 -y  && sudo apt-get -y install python3-pip

COPY  app.py /app/
WORKDIR /app

RUN pip3 install -r ../../requirements.txt
# Boot Command
CMD [flask", "run", "--host", "0.0.0.0"]
