FROM ubuntu:latest



# Install dependencies
#RUN apt-get update &&


RUN apt-get update -y && apt-get install python3 -y  && apt-get -y install python3-pip && pip3 install boto3
RUN pip3 install psycopg2 && pip3 install flask && pip3 install uwsgi


COPY  app.py /app/
WORKDIR /app
#RUN pip3 install -r requirements.txt
ENV FLASK_APP=app.py
ENV FLASK_ENV=development
# Boot Command
CMD ["flask", "run", "--host", "0.0.0.0"]
