FROM ubuntu:latest



# Install dependencies
#RUN apt-get update &&


RUN apt-get update -y && apt-get install -y python3 python3-pip

RUN pip3 install -r requirements.txt

COPY  app.py /app/
WORKDIR /app


ENV FLASK_APP=app.py
ENV FLASK_ENV=development

EXPOSE 5000
# Boot Command
CMD ["flask", "run", "--host", "0.0.0.0"]
